using System.Collections.Generic;
using System.Threading.Tasks;
using MegaCrit.Sts2.Core.Commands;                    // CreatureCmd, PlayerCmd
using MegaCrit.Sts2.Core.Entities.Cards;              // CardType, CardRarity, TargetType, CardKeyword, CardPlay
using MegaCrit.Sts2.Core.Entities.Creatures;          // Creature
using MegaCrit.Sts2.Core.GameActions.Multiplayer;     // PlayerChoiceContext
using MegaCrit.Sts2.Core.Localization.DynamicVars;    // DynamicVar, CalculationBaseVar, CalculationExtraVar, CalculatedBlockVar
using MegaCrit.Sts2.Core.Models;                      // CardModel, CardPoolModel, ModelDb
using MegaCrit.Sts2.Core.Models.CardPools;            // ColorlessCardPool
using MegaCrit.Sts2.Core.ValueProps;                  // ValueProp

namespace Sts2DebtLoan;

/// <summary>
/// 성실 납부 (Diligent Payment) — the 0-cost colorless card the 환급 (Refund) power slips into your hand on each
/// 납부. Play it for Block PURELY proportional to how diligently you've paid: <see cref="BlockPerPayment"/> for
/// every 납부 (Payment) made this combat, with NO base (0 payments = 0 Block) — but it's generated BY a payment,
/// so there's always ≥1 (<see cref="LoanService.PaymentCountThisCombat"/> — a monotonic count, NOT the spendable
/// 영수증 tally, so 정산/청구서 draining the tally doesn't shrink it). The upgraded form
/// (성실 납부+, fed by 환급+) also refunds 5 gold. Exhausts, so it doesn't clog the hand. Playing it is NOT itself a
/// 납부 (no RecordPayment → no recursion into the payment powers) and it does NOT consume the tally.
/// Block shows live via the CalculatedBlockVar pattern (same as 정산). Colorless pool (avoids the MockCardPool
/// "You monster!" getter). Auto-registered.
/// </summary>
public sealed class DiligentPaymentCard : CardModel
{
    private static CardPoolModel? _pool;
    public override CardPoolModel Pool => _pool ??= ModelDb.CardPool<ColorlessCardPool>();

    public override int MaxUpgradeLevel => 1;   // 성실 납부 vs 성실 납부+ (adds the gold refund)

    public override string PortraitPath =>
        IsUpgraded ? "res://Sts2DebtLoan/card_art/diligent_payment_plus.png"
                   : "res://Sts2DebtLoan/card_art/diligent_payment.png";
    public override string BetaPortraitPath => PortraitPath;

    public override IEnumerable<CardKeyword> CanonicalKeywords => new[] { CardKeyword.Exhaust };

    public override bool GainsBlock => true;

    private const int BaseBlock = 0;         // no base — Block is purely proportional to 납부 count
    private const int BlockPerPayment = 1;   // block for each 납부 (Payment) made this combat
    private int RefundGold => IsUpgraded ? 5 : 0;   // 성실 납부+ refunds gold on top of the block

    // {CalculatedBlock} = live total = BaseBlock + {CalculationExtra} × 납부 count; the multiplier is evaluated at
    // render (only in-combat; the count is 0 in the library), so the block on the face tracks payments with no
    // preview patch — the same scaling display 정산 uses. The "gold" var drives the +refund conditional in the loc.
    protected override IEnumerable<DynamicVar> CanonicalVars => new DynamicVar[]
    {
        new CalculationBaseVar(BaseBlock),
        new CalculationExtraVar(BlockPerPayment),
        new CalculatedBlockVar(ValueProp.Move).WithMultiplier((CardModel card, Creature? _) => LoanService.PaymentCountThisCombat(card.Owner)),
        new DynamicVar("gold", RefundGold),
    };

    public DiligentPaymentCard() : base(canonicalEnergyCost: 0, CardType.Skill, CardRarity.Event, TargetType.None) { }

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay cardPlay)
    {
        if (Owner?.Creature == null) return;
        int block = (int)DynamicVars.CalculatedBlock.Calculate(cardPlay.Target);
        if (block > 0)
            await CreatureCmd.GainBlock(Owner.Creature, block, DynamicVars.CalculatedBlock.Props, cardPlay);
        if (RefundGold > 0)
            await PlayerCmd.GainGold(RefundGold, Owner, false);
        // NOT a 납부: no LoanService.RecordPayment (recursion-safe) and no tally consumption (block reads the
        // monotonic count, which the payment powers never spend).
    }

    protected override void OnUpgrade()
    {
        base.OnUpgrade();
        DynamicVars["gold"].BaseValue = RefundGold;
    }
}
